/*
 * Generates languages/<code>.js from one shared translation table.
 *
 *   node i18n-tools/build-chrome.js
 *
 * The table below covers the site chrome — the sidebar navigation, footer and
 * common labels that appear on nearly all 85 pages. Keeping it in one place
 * avoids repeating the same English keys across 20 near-identical files.
 *
 * Brand and proper nouns (whatwhatboy, Discord, YouTube, Telegram, Instagram,
 * Twitter, TikTok, GTA V, YimMenu, Scooby Menu, Aimbot, Lua) are deliberately
 * absent: they stay in English in every language.
 *
 * To extend coverage beyond the chrome, use the round-trip workflow instead:
 *   node i18n-tools/i18n-update.js --apply    (writes languages/_todo/<lang>.js)
 *   ...translate the values there...
 *   node i18n-tools/i18n-update.js --merge
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LANGS = ['es', 'pt', 'fr', 'de', 'ru', 'tr', 'pl', 'it', 'zh', 'ja',
               'ko', 'th', 'vi', 'id', 'hi', 'sr', 'nl', 'ka', 'ar', 'he'];

// English source -> translation per language code.
const T = {
  "Home": { es:"Inicio", pt:"Início", fr:"Accueil", de:"Startseite", ru:"Главная", tr:"Ana sayfa", pl:"Strona główna", it:"Home", zh:"首页", ja:"ホーム", ko:"홈", th:"หน้าแรก", vi:"Trang chủ", id:"Beranda", hi:"होम", sr:"Почетна", nl:"Home", ka:"მთავარი", ar:"الرئيسية", he:"דף הבית" },
  "Games": { es:"Juegos", pt:"Jogos", fr:"Jeux", de:"Spiele", ru:"Игры", tr:"Oyunlar", pl:"Gry", it:"Giochi", zh:"游戏", ja:"ゲーム", ko:"게임", th:"เกม", vi:"Trò chơi", id:"Game", hi:"गेम्स", sr:"Игре", nl:"Games", ka:"თამაშები", ar:"الألعاب", he:"משחקים" },
  "Tools": { es:"Herramientas", pt:"Ferramentas", fr:"Outils", de:"Werkzeuge", ru:"Инструменты", tr:"Araçlar", pl:"Narzędzia", it:"Strumenti", zh:"工具", ja:"ツール", ko:"도구", th:"เครื่องมือ", vi:"Công cụ", id:"Alat", hi:"टूल", sr:"Алати", nl:"Hulpmiddelen", ka:"ხელსაწყოები", ar:"الأدوات", he:"כלים" },
  "Console": { es:"Consolas", pt:"Consoles", fr:"Consoles", de:"Konsolen", ru:"Консоли", tr:"Konsollar", pl:"Konsole", it:"Console", zh:"主机", ja:"コンソール", ko:"콘솔", th:"คอนโซล", vi:"Máy chơi game", id:"Konsol", hi:"कंसोल", sr:"Конзоле", nl:"Consoles", ka:"კონსოლები", ar:"أجهزة الألعاب", he:"קונסולות" },
  "Emulators": { es:"Emuladores", pt:"Emuladores", fr:"Émulateurs", de:"Emulatoren", ru:"Эмуляторы", tr:"Emülatörler", pl:"Emulatory", it:"Emulatori", zh:"模拟器", ja:"エミュレーター", ko:"에뮬레이터", th:"อีมูเลเตอร์", vi:"Trình giả lập", id:"Emulator", hi:"एमुलेटर", sr:"Емулатори", nl:"Emulators", ka:"ემულატორები", ar:"المحاكيات", he:"אמולטורים" },
  "Blog": { es:"Blog", pt:"Blog", fr:"Blog", de:"Blog", ru:"Блог", tr:"Blog", pl:"Blog", it:"Blog", zh:"博客", ja:"ブログ", ko:"블로그", th:"บล็อก", vi:"Blog", id:"Blog", hi:"ब्लॉग", sr:"Блог", nl:"Blog", ka:"ბლოგი", ar:"المدونة", he:"בלוג" },
  "Profile": { es:"Perfil", pt:"Perfil", fr:"Profil", de:"Profil", ru:"Профиль", tr:"Profil", pl:"Profil", it:"Profilo", zh:"个人资料", ja:"プロフィール", ko:"프로필", th:"โปรไฟล์", vi:"Hồ sơ", id:"Profil", hi:"प्रोफ़ाइल", sr:"Профил", nl:"Profiel", ka:"პროფილი", ar:"الملف الشخصي", he:"פרופיל" },
  "Free Cheats": { es:"Cheats gratis", pt:"Cheats grátis", fr:"Cheats gratuits", de:"Kostenlose Cheats", ru:"Бесплатные читы", tr:"Ücretsiz hileler", pl:"Darmowe cheaty", it:"Cheat gratuiti", zh:"免费作弊", ja:"無料チート", ko:"무료 치트", th:"โปรฟรี", vi:"Cheat miễn phí", id:"Cheat gratis", hi:"मुफ्त चीट", sr:"Бесплатни читови", nl:"Gratis cheats", ka:"უფასო ჩიტები", ar:"شيتات مجانية", he:"צ'יטים חינם" },
  "Game Mods": { es:"Mods de juegos", pt:"Mods de jogos", fr:"Mods de jeux", de:"Spiel-Mods", ru:"Моды для игр", tr:"Oyun modları", pl:"Mody do gier", it:"Mod per giochi", zh:"游戏模组", ja:"ゲームMOD", ko:"게임 모드", th:"ม็อดเกม", vi:"Mod game", id:"Mod game", hi:"गेम मॉड", sr:"Модови за игре", nl:"Game-mods", ka:"თამაშის მოდები", ar:"مودات الألعاب", he:"מודים למשחקים" },
  "APK Downloads": { es:"Descargas APK", pt:"Downloads de APK", fr:"Téléchargements APK", de:"APK-Downloads", ru:"Загрузки APK", tr:"APK indirmeleri", pl:"Pobieranie APK", it:"Download APK", zh:"APK 下载", ja:"APKダウンロード", ko:"APK 다운로드", th:"ดาวน์โหลด APK", vi:"Tải APK", id:"Unduhan APK", hi:"APK डाउनलोड", sr:"APK преузимања", nl:"APK-downloads", ka:"APK ჩამოტვირთვები", ar:"تنزيلات APK", he:"הורדות APK" },
  "Discord Servers": { es:"Servidores de Discord", pt:"Servidores do Discord", fr:"Serveurs Discord", de:"Discord-Server", ru:"Серверы Discord", tr:"Discord sunucuları", pl:"Serwery Discord", it:"Server Discord", zh:"Discord 服务器", ja:"Discordサーバー", ko:"디스코드 서버", th:"เซิร์ฟเวอร์ Discord", vi:"Máy chủ Discord", id:"Server Discord", hi:"डिस्कॉर्ड सर्वर", nl:"Discord-servers", sr:"Discord сервери", ka:"Discord სერვერები", ar:"سيرفرات Discord", he:"שרתי Discord" },
  "Help & FAQ": { es:"Ayuda y FAQ", pt:"Ajuda e FAQ", fr:"Aide et FAQ", de:"Hilfe & FAQ", ru:"Помощь и FAQ", tr:"Yardım ve SSS", pl:"Pomoc i FAQ", it:"Aiuto e FAQ", zh:"帮助与常见问题", ja:"ヘルプとFAQ", ko:"도움말 및 FAQ", th:"ช่วยเหลือและคำถามที่พบบ่อย", vi:"Trợ giúp & FAQ", id:"Bantuan & FAQ", hi:"सहायता और FAQ", sr:"Помоћ и честа питања", nl:"Help en FAQ", ka:"დახმარება და FAQ", ar:"المساعدة والأسئلة الشائعة", he:"עזרה ושאלות נפוצות" },
  "Help Center": { es:"Centro de ayuda", pt:"Central de ajuda", fr:"Centre d'aide", de:"Hilfecenter", ru:"Центр помощи", tr:"Yardım merkezi", pl:"Centrum pomocy", it:"Centro assistenza", zh:"帮助中心", ja:"ヘルプセンター", ko:"고객센터", th:"ศูนย์ช่วยเหลือ", vi:"Trung tâm trợ giúp", id:"Pusat bantuan", hi:"सहायता केंद्र", sr:"Центар за помоћ", nl:"Helpcentrum", ka:"დახმარების ცენტრი", ar:"مركز المساعدة", he:"מרכז העזרה" },
  "Logo": { es:"Logotipo", pt:"Logotipo", fr:"Logo", de:"Logo", ru:"Логотип", tr:"Logo", pl:"Logo", it:"Logo", zh:"标志", ja:"ロゴ", ko:"로고", th:"โลโก้", vi:"Logo", id:"Logo", hi:"लोगो", sr:"Лого", nl:"Logo", ka:"ლოგო", ar:"الشعار", he:"לוגו" },
  "Open navigation menu": { es:"Abrir menú de navegación", pt:"Abrir menu de navegação", fr:"Ouvrir le menu de navigation", de:"Navigationsmenü öffnen", ru:"Открыть меню навигации", tr:"Gezinme menüsünü aç", pl:"Otwórz menu nawigacji", it:"Apri il menu di navigazione", zh:"打开导航菜单", ja:"ナビゲーションメニューを開く", ko:"내비게이션 메뉴 열기", th:"เปิดเมนูนำทาง", vi:"Mở menu điều hướng", id:"Buka menu navigasi", hi:"नेविगेशन मेन्यू खोलें", sr:"Отвори навигациони мени", nl:"Navigatiemenu openen", ka:"ნავიგაციის მენიუს გახსნა", ar:"فتح قائمة التنقل", he:"פתח את תפריט הניווט" },
  "Toggle sidebar": { es:"Mostrar/ocultar barra lateral", pt:"Mostrar/ocultar barra lateral", fr:"Afficher/masquer la barre latérale", de:"Seitenleiste ein-/ausblenden", ru:"Показать/скрыть боковую панель", tr:"Kenar çubuğunu aç/kapat", pl:"Pokaż/ukryj panel boczny", it:"Mostra/nascondi barra laterale", zh:"切换侧边栏", ja:"サイドバーの表示切替", ko:"사이드바 전환", th:"เปิด/ปิดแถบด้านข้าง", vi:"Bật/tắt thanh bên", id:"Buka/tutup bilah sisi", hi:"साइडबार दिखाएँ/छिपाएँ", sr:"Прикажи/сакриј бочну траку", nl:"Zijbalk in-/uitklappen", ka:"გვერდითი პანელის ჩვენება/დამალვა", ar:"إظهار/إخفاء الشريط الجانبي", he:"הצג/הסתר סרגל צד" },
  "Connect With Me": { es:"Conecta conmigo", pt:"Conecte-se comigo", fr:"Retrouvez-moi", de:"Folge mir", ru:"Свяжитесь со мной", tr:"Benimle bağlantı kur", pl:"Znajdź mnie", it:"Seguimi", zh:"关注我", ja:"フォローする", ko:"함께하기", th:"ติดตามฉัน", vi:"Kết nối với tôi", id:"Terhubung dengan saya", hi:"मुझसे जुड़ें", sr:"Повежи се са мном", nl:"Volg mij", ka:"დამიკავშირდი", ar:"تواصل معي", he:"התחברו אליי" },
  "Quick Links": { es:"Enlaces rápidos", pt:"Links rápidos", fr:"Liens rapides", de:"Schnellzugriff", ru:"Быстрые ссылки", tr:"Hızlı bağlantılar", pl:"Szybkie linki", it:"Link rapidi", zh:"快速链接", ja:"クイックリンク", ko:"바로가기", th:"ลิงก์ด่วน", vi:"Liên kết nhanh", id:"Tautan cepat", hi:"त्वरित लिंक", sr:"Брзе везе", nl:"Snelle links", ka:"სწრაფი ბმულები", ar:"روابط سريعة", he:"קישורים מהירים" },
  "Support": { es:"Soporte", pt:"Suporte", fr:"Assistance", de:"Support", ru:"Поддержка", tr:"Destek", pl:"Wsparcie", it:"Assistenza", zh:"支持", ja:"サポート", ko:"지원", th:"ฝ่ายสนับสนุน", vi:"Hỗ trợ", id:"Dukungan", hi:"सपोर्ट", sr:"Подршка", nl:"Ondersteuning", ka:"მხარდაჭერა", ar:"الدعم", he:"תמיכה" },
  "Contact": { es:"Contacto", pt:"Contato", fr:"Contact", de:"Kontakt", ru:"Контакты", tr:"İletişim", pl:"Kontakt", it:"Contatti", zh:"联系", ja:"お問い合わせ", ko:"문의", th:"ติดต่อ", vi:"Liên hệ", id:"Kontak", hi:"संपर्क", sr:"Контакт", nl:"Contact", ka:"კონტაქტი", ar:"اتصل بنا", he:"צור קשר" },
  "Contact Us": { es:"Contáctanos", pt:"Fale conosco", fr:"Nous contacter", de:"Kontaktiere uns", ru:"Связаться с нами", tr:"Bize ulaşın", pl:"Skontaktuj się z nami", it:"Contattaci", zh:"联系我们", ja:"お問い合わせ", ko:"문의하기", th:"ติดต่อเรา", vi:"Liên hệ với chúng tôi", id:"Hubungi kami", hi:"हमसे संपर्क करें", sr:"Контактирај нас", nl:"Neem contact op", ka:"დაგვიკავშირდი", ar:"تواصل معنا", he:"צרו קשר" },
  "Community": { es:"Comunidad", pt:"Comunidade", fr:"Communauté", de:"Community", ru:"Сообщество", tr:"Topluluk", pl:"Społeczność", it:"Community", zh:"社区", ja:"コミュニティ", ko:"커뮤니티", th:"ชุมชน", vi:"Cộng đồng", id:"Komunitas", hi:"समुदाय", sr:"Заједница", nl:"Community", ka:"საზოგადოება", ar:"المجتمع", he:"קהילה" },
  "Download": { es:"Descargar", pt:"Baixar", fr:"Télécharger", de:"Herunterladen", ru:"Скачать", tr:"İndir", pl:"Pobierz", it:"Scarica", zh:"下载", ja:"ダウンロード", ko:"다운로드", th:"ดาวน์โหลด", vi:"Tải xuống", id:"Unduh", hi:"डाउनलोड", sr:"Преузми", nl:"Downloaden", ka:"ჩამოტვირთვა", ar:"تحميل", he:"הורדה" },
  "Go Back": { es:"Volver", pt:"Voltar", fr:"Retour", de:"Zurück", ru:"Назад", tr:"Geri dön", pl:"Wróć", it:"Indietro", zh:"返回", ja:"戻る", ko:"뒤로", th:"ย้อนกลับ", vi:"Quay lại", id:"Kembali", hi:"वापस जाएँ", sr:"Назад", nl:"Terug", ka:"უკან", ar:"رجوع", he:"חזרה" },
  "Back to top": { es:"Volver arriba", pt:"Voltar ao topo", fr:"Retour en haut", de:"Nach oben", ru:"Наверх", tr:"Yukarı dön", pl:"Do góry", it:"Torna su", zh:"回到顶部", ja:"トップへ戻る", ko:"맨 위로", th:"กลับขึ้นด้านบน", vi:"Lên đầu trang", id:"Kembali ke atas", hi:"ऊपर जाएँ", sr:"Назад на врх", nl:"Terug naar boven", ka:"დასაწყისში დაბრუნება", ar:"العودة للأعلى", he:"חזרה למעלה" },
  "Working": { es:"Funciona", pt:"Funcionando", fr:"Fonctionnel", de:"Funktioniert", ru:"Работает", tr:"Çalışıyor", pl:"Działa", it:"Funzionante", zh:"可用", ja:"動作中", ko:"작동 중", th:"ใช้งานได้", vi:"Hoạt động", id:"Berfungsi", hi:"काम कर रहा है", sr:"Ради", nl:"Werkt", ka:"მუშაობს", ar:"يعمل", he:"עובד" },
  "Active": { es:"Activo", pt:"Ativo", fr:"Actif", de:"Aktiv", ru:"Активен", tr:"Aktif", pl:"Aktywny", it:"Attivo", zh:"活跃", ja:"稼働中", ko:"활성", th:"ใช้งานอยู่", vi:"Đang hoạt động", id:"Aktif", hi:"सक्रिय", sr:"Активно", nl:"Actief", ka:"აქტიური", ar:"نشط", he:"פעיל" },
  "Available": { es:"Disponible", pt:"Disponível", fr:"Disponible", de:"Verfügbar", ru:"Доступно", tr:"Mevcut", pl:"Dostępne", it:"Disponibile", zh:"可用", ja:"利用可能", ko:"이용 가능", th:"พร้อมใช้งาน", vi:"Có sẵn", id:"Tersedia", hi:"उपलब्ध", sr:"Доступно", nl:"Beschikbaar", ka:"ხელმისაწვდომი", ar:"متاح", he:"זמין" },
  "Free": { es:"Gratis", pt:"Grátis", fr:"Gratuit", de:"Kostenlos", ru:"Бесплатно", tr:"Ücretsiz", pl:"Za darmo", it:"Gratis", zh:"免费", ja:"無料", ko:"무료", th:"ฟรี", vi:"Miễn phí", id:"Gratis", hi:"मुफ्त", sr:"Бесплатно", nl:"Gratis", ka:"უფასო", ar:"مجاني", he:"חינם" },
  "Free Access": { es:"Acceso gratuito", pt:"Acesso gratuito", fr:"Accès gratuit", de:"Kostenloser Zugang", ru:"Бесплатный доступ", tr:"Ücretsiz erişim", pl:"Darmowy dostęp", it:"Accesso gratuito", zh:"免费访问", ja:"無料アクセス", ko:"무료 이용", th:"เข้าถึงฟรี", vi:"Truy cập miễn phí", id:"Akses gratis", hi:"मुफ्त पहुँच", sr:"Бесплатан приступ", nl:"Gratis toegang", ka:"უფასო წვდომა", ar:"وصول مجاني", he:"גישה חינם" },
  "Safety": { es:"Seguridad", pt:"Segurança", fr:"Sécurité", de:"Sicherheit", ru:"Безопасность", tr:"Güvenlik", pl:"Bezpieczeństwo", it:"Sicurezza", zh:"安全", ja:"安全性", ko:"안전", th:"ความปลอดภัย", vi:"An toàn", id:"Keamanan", hi:"सुरक्षा", sr:"Безбедност", nl:"Veiligheid", ka:"უსაფრთხოება", ar:"الأمان", he:"בטיחות" },
  "Safe": { es:"Seguro", pt:"Seguro", fr:"Sûr", de:"Sicher", ru:"Безопасно", tr:"Güvenli", pl:"Bezpieczne", it:"Sicuro", zh:"安全", ja:"安全", ko:"안전", th:"ปลอดภัย", vi:"An toàn", id:"Aman", hi:"सुरक्षित", sr:"Безбедно", nl:"Veilig", ka:"უსაფრთხო", ar:"آمن", he:"בטוח" },
  "Safety Tips": { es:"Consejos de seguridad", pt:"Dicas de segurança", fr:"Conseils de sécurité", de:"Sicherheitstipps", ru:"Советы по безопасности", tr:"Güvenlik ipuçları", pl:"Wskazówki bezpieczeństwa", it:"Consigli di sicurezza", zh:"安全提示", ja:"安全のヒント", ko:"안전 팁", th:"เคล็ดลับความปลอดภัย", vi:"Mẹo an toàn", id:"Tips keamanan", hi:"सुरक्षा सुझाव", sr:"Савети за безбедност", nl:"Veiligheidstips", ka:"უსაფრთხოების რჩევები", ar:"نصائح الأمان", he:"טיפים לבטיחות" },
  "Safety Guidelines": { es:"Pautas de seguridad", pt:"Diretrizes de segurança", fr:"Consignes de sécurité", de:"Sicherheitsrichtlinien", ru:"Правила безопасности", tr:"Güvenlik kuralları", pl:"Zasady bezpieczeństwa", it:"Linee guida di sicurezza", zh:"安全指南", ja:"安全ガイドライン", ko:"안전 지침", th:"แนวทางความปลอดภัย", vi:"Hướng dẫn an toàn", id:"Panduan keamanan", hi:"सुरक्षा दिशानिर्देश", sr:"Смернице за безбедност", nl:"Veiligheidsrichtlijnen", ka:"უსაფრთხოების სახელმძღვანელო", ar:"إرشادات الأمان", he:"הנחיות בטיחות" },
  "Popular Games": { es:"Juegos populares", pt:"Jogos populares", fr:"Jeux populaires", de:"Beliebte Spiele", ru:"Популярные игры", tr:"Popüler oyunlar", pl:"Popularne gry", it:"Giochi popolari", zh:"热门游戏", ja:"人気のゲーム", ko:"인기 게임", th:"เกมยอดนิยม", vi:"Trò chơi phổ biến", id:"Game populer", hi:"लोकप्रिय गेम्स", sr:"Популарне игре", nl:"Populaire games", ka:"პოპულარული თამაშები", ar:"الألعاب الشائعة", he:"משחקים פופולריים" },
  "All Games": { es:"Todos los juegos", pt:"Todos os jogos", fr:"Tous les jeux", de:"Alle Spiele", ru:"Все игры", tr:"Tüm oyunlar", pl:"Wszystkie gry", it:"Tutti i giochi", zh:"全部游戏", ja:"すべてのゲーム", ko:"모든 게임", th:"เกมทั้งหมด", vi:"Tất cả trò chơi", id:"Semua game", hi:"सभी गेम्स", sr:"Све игре", nl:"Alle games", ka:"ყველა თამაში", ar:"كل الألعاب", he:"כל המשחקים" },
  "Video": { es:"Vídeo", pt:"Vídeo", fr:"Vidéo", de:"Video", ru:"Видео", tr:"Video", pl:"Wideo", it:"Video", zh:"视频", ja:"動画", ko:"영상", th:"วิดีโอ", vi:"Video", id:"Video", hi:"वीडियो", sr:"Видео", nl:"Video", ka:"ვიდეო", ar:"فيديو", he:"וידאו" },
  "Video Guide": { es:"Guía en vídeo", pt:"Guia em vídeo", fr:"Guide vidéo", de:"Videoanleitung", ru:"Видеоруководство", tr:"Video rehber", pl:"Poradnik wideo", it:"Guida video", zh:"视频教程", ja:"動画ガイド", ko:"영상 가이드", th:"คู่มือวิดีโอ", vi:"Hướng dẫn bằng video", id:"Panduan video", hi:"वीडियो गाइड", sr:"Видео водич", nl:"Videogids", ka:"ვიდეო სახელმძღვანელო", ar:"دليل بالفيديو", he:"מדריך וידאו" },
  "Stay Updated": { es:"Mantente al día", pt:"Fique por dentro", fr:"Restez informé", de:"Bleib auf dem Laufenden", ru:"Будь в курсе", tr:"Güncel kal", pl:"Bądź na bieżąco", it:"Resta aggiornato", zh:"保持关注", ja:"最新情報をチェック", ko:"최신 소식 받기", th:"ติดตามข่าวสาร", vi:"Luôn cập nhật", id:"Tetap ikuti kabar terbaru", hi:"अपडेट पाते रहें", sr:"Буди у току", nl:"Blijf op de hoogte", ka:"იყავი კურსში", ar:"ابقَ على اطلاع", he:"הישארו מעודכנים" },
  "Recovery": { es:"Recuperación", pt:"Recuperação", fr:"Récupération", de:"Recovery", ru:"Восстановление", tr:"Kurtarma", pl:"Recovery", it:"Recupero", zh:"恢复", ja:"リカバリー", ko:"복구", th:"การกู้คืน", vi:"Khôi phục", id:"Pemulihan", hi:"रिकवरी", sr:"Опоравак", nl:"Herstel", ka:"აღდგენა", ar:"الاستعادة", he:"שחזור" },
  "Multiplayer": { es:"Multijugador", pt:"Multijogador", fr:"Multijoueur", de:"Mehrspieler", ru:"Мультиплеер", tr:"Çok oyunculu", pl:"Tryb wieloosobowy", it:"Multigiocatore", zh:"多人游戏", ja:"マルチプレイ", ko:"멀티플레이", th:"ผู้เล่นหลายคน", vi:"Nhiều người chơi", id:"Multipemain", hi:"मल्टीप्लेयर", sr:"Више играча", nl:"Multiplayer", ka:"მრავალმოთამაშიანი", ar:"متعدد اللاعبين", he:"רב-משתתפים" },
  "Frequently Asked Questions": { es:"Preguntas frecuentes", pt:"Perguntas frequentes", fr:"Questions fréquentes", de:"Häufig gestellte Fragen", ru:"Частые вопросы", tr:"Sıkça sorulan sorular", pl:"Najczęściej zadawane pytania", it:"Domande frequenti", zh:"常见问题", ja:"よくある質問", ko:"자주 묻는 질문", th:"คำถามที่พบบ่อย", vi:"Câu hỏi thường gặp", id:"Pertanyaan yang sering diajukan", hi:"अक्सर पूछे जाने वाले सवाल", sr:"Често постављана питања", nl:"Veelgestelde vragen", ka:"ხშირად დასმული კითხვები", ar:"الأسئلة الشائعة", he:"שאלות נפוצות" },
  "System Requirements": { es:"Requisitos del sistema", pt:"Requisitos do sistema", fr:"Configuration requise", de:"Systemanforderungen", ru:"Системные требования", tr:"Sistem gereksinimleri", pl:"Wymagania systemowe", it:"Requisiti di sistema", zh:"系统要求", ja:"動作環境", ko:"시스템 요구 사항", th:"ความต้องการของระบบ", vi:"Yêu cầu hệ thống", id:"Persyaratan sistem", hi:"सिस्टम आवश्यकताएँ", sr:"Системски захтеви", nl:"Systeemvereisten", ka:"სისტემური მოთხოვნები", ar:"متطلبات النظام", he:"דרישות מערכת" },
  "Join Discord": { es:"Únete a Discord", pt:"Entrar no Discord", fr:"Rejoindre Discord", de:"Discord beitreten", ru:"Присоединиться к Discord", tr:"Discord'a katıl", pl:"Dołącz do Discorda", it:"Entra su Discord", zh:"加入 Discord", ja:"Discordに参加", ko:"디스코드 참여", th:"เข้าร่วม Discord", vi:"Tham gia Discord", id:"Gabung Discord", hi:"डिस्कॉर्ड जॉइन करें", sr:"Придружи се Discord-у", nl:"Word lid van Discord", ka:"შემოგვიერთდი Discord-ზე", ar:"انضم إلى Discord", he:"הצטרפו ל-Discord" },
  "Official Site": { es:"Sitio oficial", pt:"Site oficial", fr:"Site officiel", de:"Offizielle Seite", ru:"Официальный сайт", tr:"Resmî site", pl:"Oficjalna strona", it:"Sito ufficiale", zh:"官方网站", ja:"公式サイト", ko:"공식 사이트", th:"เว็บไซต์ทางการ", vi:"Trang chính thức", id:"Situs resmi", hi:"आधिकारिक साइट", sr:"Званични сајт", nl:"Officiële site", ka:"ოფიციალური საიტი", ar:"الموقع الرسمي", he:"אתר רשמי" },
  "Visit Site": { es:"Visitar sitio", pt:"Visitar site", fr:"Visiter le site", de:"Seite besuchen", ru:"Перейти на сайт", tr:"Siteyi ziyaret et", pl:"Odwiedź stronę", it:"Visita il sito", zh:"访问网站", ja:"サイトを見る", ko:"사이트 방문", th:"เยี่ยมชมเว็บไซต์", vi:"Truy cập trang", id:"Kunjungi situs", hi:"साइट देखें", sr:"Посети сајт", nl:"Site bezoeken", ka:"საიტის ნახვა", ar:"زيارة الموقع", he:"בקרו באתר" },
  "Source Code": { es:"Código fuente", pt:"Código-fonte", fr:"Code source", de:"Quellcode", ru:"Исходный код", tr:"Kaynak kodu", pl:"Kod źródłowy", it:"Codice sorgente", zh:"源代码", ja:"ソースコード", ko:"소스 코드", th:"ซอร์สโค้ด", vi:"Mã nguồn", id:"Kode sumber", hi:"सोर्स कोड", sr:"Изворни код", nl:"Broncode", ka:"წყაროს კოდი", ar:"الكود المصدري", he:"קוד מקור" },
  "Open Source": { es:"Código abierto", pt:"Código aberto", fr:"Open source", de:"Open Source", ru:"Открытый исходный код", tr:"Açık kaynak", pl:"Open source", it:"Open source", zh:"开源", ja:"オープンソース", ko:"오픈 소스", th:"โอเพนซอร์ส", vi:"Mã nguồn mở", id:"Sumber terbuka", hi:"ओपन सोर्स", sr:"Отворен код", nl:"Open source", ka:"ღია კოდი", ar:"مفتوح المصدر", he:"קוד פתוח" },
  "Trusted Sources": { es:"Fuentes confiables", pt:"Fontes confiáveis", fr:"Sources fiables", de:"Vertrauenswürdige Quellen", ru:"Надёжные источники", tr:"Güvenilir kaynaklar", pl:"Zaufane źródła", it:"Fonti affidabili", zh:"可信来源", ja:"信頼できる入手先", ko:"신뢰할 수 있는 출처", th:"แหล่งที่เชื่อถือได้", vi:"Nguồn đáng tin cậy", id:"Sumber tepercaya", hi:"विश्वसनीय स्रोत", sr:"Поуздани извори", nl:"Betrouwbare bronnen", ka:"სანდო წყაროები", ar:"مصادر موثوقة", he:"מקורות אמינים" },
  "No results found matching your search.": { es:"No se encontraron resultados para tu búsqueda.", pt:"Nenhum resultado encontrado para sua busca.", fr:"Aucun résultat ne correspond à votre recherche.", de:"Keine Ergebnisse für deine Suche gefunden.", ru:"По вашему запросу ничего не найдено.", tr:"Aramanızla eşleşen sonuç bulunamadı.", pl:"Nie znaleziono wyników pasujących do wyszukiwania.", it:"Nessun risultato corrisponde alla tua ricerca.", zh:"未找到符合搜索条件的结果。", ja:"検索条件に一致する結果は見つかりませんでした。", ko:"검색과 일치하는 결과가 없습니다.", th:"ไม่พบผลลัพธ์ที่ตรงกับการค้นหาของคุณ", vi:"Không tìm thấy kết quả nào khớp với tìm kiếm của bạn.", id:"Tidak ada hasil yang cocok dengan pencarian Anda.", hi:"आपकी खोज से मेल खाता कोई परिणाम नहीं मिला।", sr:"Нема резултата који одговарају претрази.", nl:"Geen resultaten gevonden voor je zoekopdracht.", ka:"თქვენს ძიებას შესაბამისი შედეგი ვერ მოიძებნა.", ar:"لم يتم العثور على نتائج مطابقة لبحثك.", he:"לא נמצאו תוצאות התואמות את החיפוש שלך." },
  "No image available": { es:"Imagen no disponible", pt:"Imagem indisponível", fr:"Aucune image disponible", de:"Kein Bild verfügbar", ru:"Изображение недоступно", tr:"Görsel yok", pl:"Brak obrazu", it:"Nessuna immagine disponibile", zh:"暂无图片", ja:"画像がありません", ko:"이미지 없음", th:"ไม่มีรูปภาพ", vi:"Không có hình ảnh", id:"Gambar tidak tersedia", hi:"कोई छवि उपलब्ध नहीं", sr:"Слика није доступна", nl:"Geen afbeelding beschikbaar", ka:"სურათი მიუწვდომელია", ar:"لا توجد صورة", he:"אין תמונה זמינה" },
  "Full Size Image": { es:"Imagen a tamaño completo", pt:"Imagem em tamanho real", fr:"Image en taille réelle", de:"Bild in voller Größe", ru:"Изображение в полном размере", tr:"Tam boyutlu görsel", pl:"Obraz w pełnym rozmiarze", it:"Immagine a dimensione intera", zh:"查看原图", ja:"フルサイズ画像", ko:"원본 크기 이미지", th:"ภาพขนาดเต็ม", vi:"Ảnh kích thước đầy đủ", id:"Gambar ukuran penuh", hi:"पूर्ण आकार छवि", sr:"Слика у пуној величини", nl:"Afbeelding op ware grootte", ka:"სრული ზომის სურათი", ar:"صورة بالحجم الكامل", he:"תמונה בגודל מלא" },
  "Disclaimer:": { es:"Aviso:", pt:"Aviso:", fr:"Avertissement :", de:"Haftungsausschluss:", ru:"Отказ от ответственности:", tr:"Uyarı:", pl:"Zastrzeżenie:", it:"Avvertenza:", zh:"免责声明：", ja:"免責事項：", ko:"면책 조항:", th:"ข้อจำกัดความรับผิดชอบ:", vi:"Miễn trừ trách nhiệm:", id:"Penafian:", hi:"अस्वीकरण:", sr:"Одрицање одговорности:", nl:"Disclaimer:", ka:"პასუხისმგებლობის შეზღუდვა:", ar:"إخلاء مسؤولية:", he:"כתב ויתור:" },
  "Educational purposes only. Use at your own risk.": { es:"Solo con fines educativos. Úsalo bajo tu propia responsabilidad.", pt:"Apenas para fins educacionais. Use por sua conta e risco.", fr:"À des fins éducatives uniquement. Utilisation à vos propres risques.", de:"Nur zu Bildungszwecken. Nutzung auf eigene Gefahr.", ru:"Только в образовательных целях. Используйте на свой риск.", tr:"Yalnızca eğitim amaçlıdır. Sorumluluk size aittir.", pl:"Wyłącznie w celach edukacyjnych. Używasz na własne ryzyko.", it:"Solo a scopo didattico. Usa a tuo rischio.", zh:"仅供学习用途，使用风险自负。", ja:"教育目的のみ。自己責任でご利用ください。", ko:"교육 목적으로만 제공됩니다. 사용에 따른 책임은 본인에게 있습니다.", th:"เพื่อการศึกษาเท่านั้น ใช้งานด้วยความเสี่ยงของคุณเอง", vi:"Chỉ dùng cho mục đích giáo dục. Tự chịu rủi ro khi sử dụng.", id:"Hanya untuk tujuan edukasi. Gunakan dengan risiko sendiri.", hi:"केवल शैक्षिक उद्देश्यों के लिए। उपयोग अपने जोखिम पर करें।", sr:"Само у образовне сврхе. Користите на сопствену одговорност.", nl:"Alleen voor educatieve doeleinden. Gebruik op eigen risico.", ka:"მხოლოდ საგანმანათლებლო მიზნით. გამოიყენეთ საკუთარი რისკით.", ar:"لأغراض تعليمية فقط. الاستخدام على مسؤوليتك.", he:"למטרות לימוד בלבד. השימוש באחריותכם." },
  "All content is for educational purposes only. Use at your own risk. We are not responsible for any bans or consequences.": { es:"Todo el contenido es solo con fines educativos. Úsalo bajo tu propia responsabilidad. No nos hacemos responsables de baneos ni consecuencias.", pt:"Todo o conteúdo é apenas para fins educacionais. Use por sua conta e risco. Não nos responsabilizamos por banimentos ou consequências.", fr:"Tout le contenu est fourni à des fins éducatives uniquement. Utilisation à vos propres risques. Nous ne sommes pas responsables des bannissements ou conséquences.", de:"Alle Inhalte dienen nur Bildungszwecken. Nutzung auf eigene Gefahr. Wir haften nicht für Sperren oder Folgen.", ru:"Весь контент предназначен только для образовательных целей. Используйте на свой риск. Мы не несём ответственности за баны и последствия.", tr:"Tüm içerik yalnızca eğitim amaçlıdır. Sorumluluk size aittir. Banlardan veya sonuçlardan sorumlu değiliz.", pl:"Cała zawartość służy wyłącznie celom edukacyjnym. Używasz na własne ryzyko. Nie odpowiadamy za bany ani konsekwencje.", it:"Tutti i contenuti sono solo a scopo didattico. Usa a tuo rischio. Non siamo responsabili di ban o conseguenze.", zh:"所有内容仅供学习用途，使用风险自负。我们不对任何封禁或后果负责。", ja:"すべての内容は教育目的のみです。自己責任でご利用ください。BANやその結果について当方は責任を負いません。", ko:"모든 콘텐츠는 교육 목적으로만 제공됩니다. 사용에 따른 책임은 본인에게 있으며, 밴이나 그 결과에 대해 책임지지 않습니다.", th:"เนื้อหาทั้งหมดมีไว้เพื่อการศึกษาเท่านั้น ใช้งานด้วยความเสี่ยงของคุณเอง เราไม่รับผิดชอบต่อการแบนหรือผลที่ตามมา", vi:"Toàn bộ nội dung chỉ dùng cho mục đích giáo dục. Tự chịu rủi ro khi sử dụng. Chúng tôi không chịu trách nhiệm về việc bị cấm hay hậu quả nào.", id:"Semua konten hanya untuk tujuan edukasi. Gunakan dengan risiko sendiri. Kami tidak bertanggung jawab atas ban atau konsekuensi apa pun.", hi:"सारी सामग्री केवल शैक्षिक उद्देश्यों के लिए है। उपयोग अपने जोखिम पर करें। किसी भी बैन या परिणाम के लिए हम जिम्मेदार नहीं हैं।", sr:"Сав садржај је искључиво у образовне сврхе. Користите на сопствену одговорност. Не одговарамо за банове нити последице.", nl:"Alle inhoud is uitsluitend voor educatieve doeleinden. Gebruik op eigen risico. Wij zijn niet verantwoordelijk voor bans of gevolgen.", ka:"სრული შინაარსი მხოლოდ საგანმანათლებლო მიზნისთვისაა. გამოიყენეთ საკუთარი რისკით. ჩვენ არ ვაგებთ პასუხს ბანებზე ან შედეგებზე.", ar:"كل المحتوى لأغراض تعليمية فقط. الاستخدام على مسؤوليتك. لسنا مسؤولين عن أي حظر أو عواقب.", he:"כל התוכן נועד למטרות לימוד בלבד. השימוש באחריותכם. איננו אחראים לחסימות או להשלכות כלשהן." },
  "Content creator. Building gaming communities and creating educational content.": { es:"Creador de contenido. Construyo comunidades de jugadores y creo contenido educativo.", pt:"Criador de conteúdo. Construindo comunidades de jogadores e criando conteúdo educacional.", fr:"Créateur de contenu. Je construis des communautés de joueurs et crée du contenu éducatif.", de:"Content Creator. Ich baue Gaming-Communitys auf und erstelle Lerninhalte.", ru:"Контент-мейкер. Развиваю игровые сообщества и создаю обучающий контент.", tr:"İçerik üreticisi. Oyun toplulukları kuruyor ve eğitici içerik üretiyorum.", pl:"Twórca treści. Buduję społeczności graczy i tworzę materiały edukacyjne.", it:"Creator di contenuti. Costruisco community di gioco e creo contenuti educativi.", zh:"内容创作者。打造游戏社区，制作教学内容。", ja:"コンテンツクリエイター。ゲームコミュニティを育て、教育的なコンテンツを作っています。", ko:"콘텐츠 크리에이터. 게임 커뮤니티를 만들고 교육 콘텐츠를 제작합니다.", th:"ครีเอเตอร์คอนเทนต์ สร้างชุมชนเกมและทำคอนเทนต์เพื่อการเรียนรู้", vi:"Nhà sáng tạo nội dung. Xây dựng cộng đồng game và làm nội dung mang tính giáo dục.", id:"Kreator konten. Membangun komunitas gaming dan membuat konten edukatif.", hi:"कंटेंट क्रिएटर। गेमिंग समुदाय बनाना और शैक्षिक कंटेंट तैयार करना।", sr:"Креатор садржаја. Градим гејмерске заједнице и правим едукативни садржај.", nl:"Contentmaker. Ik bouw gamingcommunity's en maak educatieve content.", ka:"კონტენტის შემქმნელი. ვაშენებ გეიმინგ საზოგადოებებს და ვქმნი საგანმანათლებლო კონტენტს.", ar:"صانع محتوى. أبني مجتمعات الألعاب وأصنع محتوى تعليميًا.", he:"יוצר תוכן. בונה קהילות גיימינג ומייצר תוכן לימודי." }
};

// ---------------------------------------------------------------- generate ---
const keys = Object.keys(T);
let written = 0;

for (const code of LANGS) {
  const entries = keys
    .filter(k => T[k][code])
    .map(k => '    ' + JSON.stringify(k) + ': ' + JSON.stringify(T[k][code]) + ',');

  const out =
`/* ${code} — whatwhatboy site dictionary.
   Generated by i18n-tools/build-chrome.js — edit the table there, not this file.
   Covers the sidebar navigation, footer and shared labels across all pages.
   Brand names and cheat jargon deliberately stay in English. */
(function () {
  var t = {
${entries.join('\n').replace(/,$/, '')}
  };

  if (window.__scoobyI18n) window.__scoobyI18n.register(${JSON.stringify(code)}, t);
  else (window.__scoobyI18nQueue = window.__scoobyI18nQueue || []).push([${JSON.stringify(code)}, t]);
})();
`;
  fs.writeFileSync(path.join(ROOT, 'languages', code + '.js'), out, 'utf8');
  written++;
}

console.log('table entries : ' + keys.length);
console.log('languages     : ' + LANGS.length);
console.log('dictionaries  : ' + written + ' written to languages/');
